### PR TITLE
Upgrade Monocypher to 4.0.1

### PR DESCRIPTION
**Pull request by mchack-work**

### CODE REVIEW

**Comment by mchack-work** [comment]
Test with: https://github.com/tillitis/tkey-device-signer/pull/4

**Comment by dehanj** [comment]
From initial tests it seems to produce an expected result. Tested with https://github.com/tillitis/tkey-device-signer/pull/4 and tkey-sign-cli.

**Comment by dehanj** [comment]
What is left for this to be ready?

**Review by dehanj — APPROVED** [review]
Looks good.
Tested with ssh-agent.

**Pull request merged**
