### PR TITLE
Use stdint.h/stddef.h

### LINKED ISSUE #21: Use stdint.h
For better compatibility when porting other code to TKey, use clang's stdint.h instead of our own types.h

### PR DESCRIPTION
**Pull request by mchack-work**
Use clang's stdint.h and stddef.h instead of our own types. Please try it out with a device app.

Closes #21

### CODE REVIEW

**Comment by iknek** [comment]
Built tkey-signer device app. Loaded with tkey-sign-cli. Works as expected.

**Review by dehanj — APPROVED** [review]

**Comment by dehanj** [comment]
Tested.
This is still a draft. Is that intentional?

**Comment by mchack-work** [comment]
Yes, until we see that the rest of our apps are satisfied with these header files. I just tried device-fido and it works after including stdint.h and stddef.h in places.

**Comment by quite** [comment]
tkey-device-x25519 is satisfied.

**Pull request merged**
